name: app
runtime: python39
services:
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: credit-portfolio-risk-monitoring/app
  name: app
entrypoint: gunicorn --worker-tmp-dir /dev/shm app.wsgi --timeout 120